// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MadeWithMv","status":false,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"console_log","status":true,"description":"Shows the developer console on boot.","parameters":{"Console Width":"800","Console Height":"300","Console X-Position":"0","Console Y-Position":"0","Game Window X-Offset":"150","Game Window Y-Offset":"0","Autofocus":"true"}},
{"name":"tutorial1","status":false,"description":"","parameters":{}},
{"name":"Tutorial","status":true,"description":"","parameters":{}},
{"name":"Tutorial24","status":true,"description":"","parameters":{}}
];
